[package]
name = "anndata-memory"
version = "1.0.4"
edition = "2021"
readme = "README.md"
repository = "https://github.com/SingleRust/Anndata-Memory"
description = "Thread-safe AnnData-like structure for single-cell genomics data in Rust. Provides controlled mutability, efficient memory management, and flexible data manipulation. Ideal for concurrent bioinformatics applications."
include = [
    "**/*.rs",
    "Cargo.toml",
]
license-file = "LICENSE.md"

[dependencies]
anyhow = "1.0"
log = "0.4"
ndarray = { version = "0.16.1", features = ["rayon"] }
nalgebra = { version = "0.33.2", features = ["serde-serialize", "rayon"] }
nalgebra-sparse = "0.10.0"
polars = { version = "0.45.1", features = [
    "lazy",
    "decompress-fast",
    "ndarray",
    "dtype-full",
] }
parking_lot = "0.12"
anndata = "0.6.1"
anndata-hdf5 = "0.5.0"


[dev-dependencies]
tempfile = "3.14.0"
proptest = "1.6.0"
rand = "0.8.5"
ndarray-rand = "0.15.0"
nalgebra = { version = "0.33.2", features = ["rand"] }