[package]
name = "anndata-memory"
version = "1.0.7"
edition = "2021"
readme = "README.md"
repository = "https://github.com/SingleRust/Anndata-Memory"
description = "Thread-safe AnnData-like structure for single-cell genomics data in Rust. Provides controlled mutability, efficient memory management, and flexible data manipulation. Ideal for concurrent bioinformatics applications."
include = [
    "**/*.rs",
    "Cargo.toml",
]
license-file = "LICENSE.md"

[dependencies]
anyhow = "1.0"
log = "0.4"
ndarray = { version = "0.17", features = ["rayon"] }
polars = { version = "0.53", features = [
    "lazy",
    "ndarray",
    "dtype-full",
] }
parking_lot = "0.12"
anndata = {git="https://github.com/SingleRust/anndata-rs", branch = "sparse-rewrite", package = "anndata" }
anndata-hdf5 = {git="https://github.com/SingleRust/anndata-rs", branch = "sparse-rewrite", package = "anndata-hdf5" }
anndata-zarr = {git="https://github.com/SingleRust/anndata-rs", branch = "sparse-rewrite", package = "anndata-zarr" }
sprs = "0.11.4"


[dev-dependencies]
tempfile = "3.14.0"
rand = "0.8.5"
